# Generated by Django 3.2.13 on 2022-11-27 08:32

import anuario.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('anuario', '0002_auto_20221117_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='turma',
            new_name='_turma',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='aluno',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default='images/alunos/perfil/default_profile', upload_to=anuario.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='aluno',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.CharField(choices=[('INF', 'Informática'), ('ADM', 'Administração')], default='INF', max_length=3),
        ),
        migrations.AddField(
            model_name='turma',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='foto',
            field=models.ImageField(default='images/turmas/default_turma.png', upload_to=anuario.models.path_and_renameTurma),
        ),
        migrations.AddField(
            model_name='turma',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='representante', to='anuario.aluno'),
        ),
        migrations.AddField(
            model_name='turma',
            name='viceRep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='viceRep', to='anuario.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='anoDaFormatura',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=anuario.models.path_and_rename)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
