# Generated by Django 3.2.13 on 2022-11-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0003_auto_20221127_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='_turma',
            new_name='turma',
        ),
    ]
