# Generated by Django 3.2.13 on 2022-11-28 10:47

import anuario.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuario', '0004_rename__turma_aluno_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='object_id',
        ),
        migrations.AddField(
            model_name='foto',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foto',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='foto',
            name='descricao',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='foto',
            name='galeria_da_turma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foto',
            name='pessoas',
            field=models.ManyToManyField(blank=True, related_name='pessoas', to='anuario.Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default='images/alunos/perfil/default_profile.png', upload_to=anuario.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to=anuario.models.path_and_renameFoto),
        ),
    ]
