# Generated by Django 3.2.13 on 2023-01-03 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuario', '0005_auto_20221128_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='pessoas',
        ),
        migrations.CreateModel(
            name='postit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
                ('folha', models.CharField(choices=[('p', 'Post It'), ('f', 'folha A4'), ('c', 'Folha de Caderno')], max_length=1)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
