# Generated by Django 3.2.13 on 2023-01-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0006_auto_20230103_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postit',
            name='folha',
        ),
    ]
