# Generated by Django 3.2.13 on 2023-01-04 03:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0007_remove_postit_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='descricao',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='descricao',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
