# Generated by Django 3.2.13 on 2023-01-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0008_auto_20230104_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='anuario.aluno'),
        ),
    ]
