# Generated by Django 3.2.13 on 2023-01-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0010_alter_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='postit',
            name='folha',
            field=models.CharField(choices=[('P', 'Post-it'), ('F', 'Folha')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=' ', max_length=400),
        ),
    ]
