# Generated by Django 3.2.13 on 2023-01-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuario', '0012_auto_20230105_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capa',
            field=models.ImageField(default='images/logos/news_default.jpg', upload_to='images/posts'),
        ),
    ]
